TriviaGame/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace TriviaGame.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TriviaGame/Pages/Game.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services;
using Services.Model;

namespace TriviaGame.Pages
{
    [BindProperties(SupportsGet = true)]
    public class GameModel : PageModel
    {
        private readonly IGameServices service;

        public GameModel(IGameServices service)
        {
            this.service = service;
            GameData = new GameData();
        }


        public GameData GameData { get; set; }
        public int User_Id { get; set; }
        public async Task OnGetAsync(int user_id)
        {
            GameData = await service.GetGameData(user_id);
            if (!string.IsNullOrEmpty(GameData.Message))
            {
                TempData["IsCorrect"] = null;
            }
        }

        public async Task<IActionResult> OnPostAnswerQuestionAsync(int userId, int questionId, int answerId)
        {
            GameData = await service.AnswerQuestion(userId, questionId, answerId);
            TempData["IsCorrect"] = GameData.AnswerIsCorrect ? "True" : "False";

            return RedirectToAction("OnGetAsync", new { user_id = userId });

        }
    }
}

TriviaGame/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TriviaGame.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

TriviaGame/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TriviaGame.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TriviaGame/Pages/Game.cshtml
@page
@model TriviaGame.Pages.GameModel

@if (Model.GameData.User != null)
{

    <div class="container row p-0 m-0">
        <div class="col-6">
            <p>User Id: @Model.GameData.User.Id</p>

        </div>
    </div>
    <div class="container row p-0 m-0">
        <div class="col-6">
            <p>@Model.GameData.PlayedCount / @Model.GameData.MaxPlayCount</p>

        </div>
        <div class="col-6 text-right">
            <p>Score: @Model.GameData.User.Score</p>

        </div>

    </div>
}
@if (string.IsNullOrEmpty(Model.GameData.Message) && Model.GameData.Question != null)
{
    <div class="container row p-0 m-0">

        <div class="col-12 text-center">
            <h2>@Model.GameData.Question.Text </h2>

        </div>
    </div>
    <form method="post">
        <div class="container row p-0 m-0">

            <div class="col-6">
                <button class="btn btn-info form-control text-white"
                        asp-page-handler="AnswerQuestion" asp-route-userId="@Model.User_Id"
                        asp-route-questionId="@Model.GameData.Question.Id"
                        asp-route-answerId="@Model.GameData.Question.Answers[0].Id">
                    @Model.GameData.Question.Answers[0].Text
                </button>
            </div>
            <div class="col-6">
                <button class="btn btn-info form-control text-white"
                        asp-page-handler="AnswerQuestion" asp-route-userId="@Model.User_Id"
                        asp-route-questionId="@Model.GameData.Question.Id"
                        asp-route-answerId="@Model.GameData.Question.Answers[1].Id">
                    @Model.GameData.Question.Answers[1].Text
                </button>
            </div>

        </div>
    </form>
    <div class="container row p-0 m-0">
        <div class="col-12 text-center">
            @if (TempData.ContainsKey("IsCorrect"))
            {
                @if ((string)TempData["IsCorrect"] == "True")
                {
                    <div class="alert alert-success" role="alert">
                        Answer was Right!
                    </div>
                }
                else if ((string)TempData["IsCorrect"] == "False")
                {
                    <div class="alert alert-danger" role="alert">
                        Answer was Wrong!
                    </div>

                }
            }


        </div>
    </div>
}
else
{
    <p>@Model.GameData.Message</p>
}

TriviaGame/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TriviaGame/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TriviaGame</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-page="/Index">TriviaGame</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>*@
                @*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Game">Privacy</a>
                            </li>
                        </ul>
                    </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TriviaGame - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>